apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: alb-tg-binding-prod
spec:
  serviceRef:
    name: cilium-ingress
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:837411785224:targetgroup/the-redemption-alb-tg/05b51b5ecf5eba7b
