apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  description: Application workloads for the production cluster
  sourceRepos:
    - https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
    - https://github.com/khantnaingset-kns/the-redemption-helm-charts
  destinations:
    - namespace: the-redemption
      server: https://kubernetes.default.svc
    - namespace: the-redemption
      name: in-cluster
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: Job
    - group: external-secrets.io
      kind: ExternalSecret
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: networking.k8s.io
      kind: Ingress
    - group: policy
      kind: PodDisruptionBudget
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
