apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Application workloads for the production cluster
  sourceRepos:
    - https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
    - https://github.com/khantnaingset-kns/the-redemption-helm-charts
  destinations:
    - namespace: the-redemption
      server: https://kubernetes.default.svc
    - namespace: the-redemption
      name: in-cluster
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
