apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-redemption-api
  namespace: argocd
spec:
  project: applications
  sources:
    - repoURL: https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
      targetRevision: main
      ref: argocd_values

    - repoURL: https://github.com/khantnaingset-kns/the-redemption-helm-charts
      targetRevision: main
      path: the-redemption-api
      helm:
        valueFiles:
          - $argocd_values/applications/the-redemption-api/values.yaml

  destination:
    namespace: the-redemption
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
