tolerations:
  - key: workload-tier
    value: general-purpose
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload-tier
              operator: In
              values:
                - general-purpose

hostNetwork:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

replicas: 1

args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP
