clusterName: prod-the-redemption
autoDiscoverAwsVpcID: true

image:
  tag: v2.12.0

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

tolerations:
  - key: workload-tier
    value: general-purpose
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload-tier
              operator: In
              values:
                - general-purpose

serviceAccount:
  create: true
  name: aws-load-balancer-controller-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::837411785224:role/alb-controller-irsa-20260525071350952400000001"