apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-160"
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
      targetRevision: main
      ref: argocd_values

    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.8.26
      helm:
        valueFiles:
          - $argocd_values/infrastructure/argocd/values.yaml

  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
