apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret-operator
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
      targetRevision: main
      path: infrastructure/external-secret-operator
      ref: argocd_values

    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.16.1
      helm:
        valueFiles:
          - $argocd_values/infrastructure/external-secret-operator/values.yaml

  destination:
    namespace: utilities
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
