apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-140"
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
      targetRevision: main
      ref: argocd_values

    - repoURL: https://github.com/khantnaingset-kns/the-redemption-helm-charts
      targetRevision: main
      path: network-policies
      helm:
        valueFiles:
          - $argocd_values/infrastructure/network-policies/values.yaml

  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
