apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodepools
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-130"
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
      targetRevision: main
      path: infrastructure/nodepools
      ref: argocd_values

    - repoURL: https://github.com/khantnaingset-kns/the-redemption-helm-charts
      targetRevision: main
      path: nodepools
      helm:
        valueFiles:
          - $argocd_values/infrastructure/nodepools/values.yaml

  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
