apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-120"
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
      targetRevision: main
      ref: argocd_values

    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 69.8.2
      helm:
        valueFiles:
          - $argocd_values/infrastructure/prometheus-operator/values.yaml

    - repoURL: https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
      targetRevision: main
      path: infrastructure/prometheus-operator/alerts

  destination:
    namespace: o11y
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
