apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/khantnaingset-kns/the-redemption-gitops-prod.git
      targetRevision: main
      path: infrastructure/redis/manifests
  destination:
    namespace: utilities
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
